export enum ContentRating {
  U = "U",
  UA7Plus = "U/A 7+",
  UA13Plus = "U/A 13+",
  UA16Plus = "U/A 16+",
  EighteenPlus = "18+",
}

export enum Language {
  English = "English",
  Hindi = "Hindi",
  Tamil = "Tamil",
  Telugu = "Telugu",
  Kannada = "Kannada",
  Malayalam = "Malayalam",
  Bengali = "Bengali",
  Marathi = "Marathi",
  Gujarati = "Gujarati",
  Punjabi = "Punjabi",
  Urdu = "Urdu",
  Spanish = "Spanish",
  French = "French",
  German = "German",
  Chinese = "Chinese",
  Japanese = "Japanese",
  Korean = "Korean",
  Arabic = "Arabic",
  Russian = "Russian",
}

export enum Genre {
  Action = "Action",
  Drama = "Drama",
  Comedy = "Comedy",
  Thriller = "Thriller",
  Romance = "Romance",
  Horror = "Horror",
  SciFi = "Science Fiction",
  Fantasy = "Fantasy",
  Adventure = "Adventure",
  Mystery = "Mystery",
  Animation = "Animation",
  Documentary = "Documentary",
  Musical = "Musical",
  Family = "Family",
  Crime = "Crime",
  History = "History",
  War = "War",
  Western = "Western",
  Reality = "Reality",
  TalkShow = "Talk Show",
}
